### ISSUE TITLE
Compile failure using ISP DNS for notresolvabledomain test

### ISSUE THREAD

**Issue by tcprst** [pacparser/pacparser#83] opened 2016-08-31 12:52 UTC
Hi @manugarg 

I was compiling the pacparser library today when I noticed something strange.  The host I was installing it on happened to use an upstream ISP DNS server that shadily responds to queries for non-existent domains to serve their advertising campaign.  This naturally caused the test to fail and I had to add the INTERNET_REQUIRED to that line in the test data and then export the NO_INTERNET environment variable so it would compile successfully.  

I just thought you might want to add something in the INSTALL document to cover this case if you deem it common enough to matter.

Anyway just wanted to let you know of this case.

Best regards,
tcprst

**Comment by manugarg** [comment] 2016-09-24 18:00
It's a duplicate of #79.

**Closed by manugarg** 2016-09-24 18:00 UTC
Labels: duplicate
